# Generated by Django 4.1.2 on 2022-10-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bodypart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
